---
title: "proj1"
author: "mcdevitt"
date: "8 mars 2017"
output:
  md_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(repmis)
library(RCurl)
library(methods)
library(ggplot2)
library(pastecs)

require (reshape2)
require (xtable)
require (ascii)

```


## R Markdown


```{r read_data, message = FALSE}


# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	gdp data in & clean
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv"
download.file(url, destfile = "./GDP.csv")
gdp <- read.csv("GDP.csv", sep = ",",
				header = FALSE,
				skip = 5,
				stringsAsFactors = FALSE)

gdp_names <- c("country_code", "rank", "aaa", "country_name", "economy_dollars")
names(gdp) <- gdp_names

gdp$rank <- as.integer(gdp$rank)
gdp <- gdp[!is.na(gdp$rank),]

gdp$economy_dollars <- gsub(",", "", gdp$economy_dollars)
gdp$economy_dollars <- as.numeric(gdp$economy_dollars)

gdp[3] <- NULL
width <- dim(gdp)[2]
gdp[5:width] <- NULL

# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# ...	educational data in & clean
# ...	-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv"
download.file(url, destfile = "./EDSTATS_Country.csv")
edu <- read.csv("EDSTATS_Country.csv", sep = ",",
				header = TRUE,
				skip = 0,
				stringsAsFactors = FALSE)

width <- dim(edu)[2]
edu[5:width] <- NULL


gdp_edu <- merge(gdp, edu, by.x = "country_code", by.y = "CountryCode")
```


```{r rename_variables}

gdp_edu[gdp_edu$Income.Group == "High income: OECD",   ]$Income.Group <- "1_High_OECD" 
gdp_edu[gdp_edu$Income.Group == "High income: nonOECD",]$Income.Group <- "2_High_nonOECD" 
gdp_edu[gdp_edu$Income.Group == "Upper middle income", ]$Income.Group <- "3_Upper_Middle" 
gdp_edu[gdp_edu$Income.Group == "Lower middle income", ]$Income.Group <- "4_Lower_Middle" 
gdp_edu[gdp_edu$Income.Group == "Low income",          ]$Income.Group <- "5_Low_Income" 

save(gdp_edu, file = "../gdp_edu.Rda")
```
Data is now gathered, cleaned, merged into one data frame

```{r}
str(gdp_edu)

summary(gdp_edu)

names(gdp_edu)

dim(gdp_edu)

boxplot(log10(gdp_edu$economy_dollars) ~ gdp_edu$Region)


```


